apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "appdeployment.name" . }}-configmap
  namespace: {{ .Release.Namespace }}
data:
  # Configuration values can be set as key-value properties
  DB_FLY_ADDRESS: {{ .Values.configVars.DbFlywayAddress | quote }}
  DB_ADDRESS: {{ .Values.configVars.DbAddress | quote }}
  DB_NAME: {{ .Values.configVars.DbName | quote }}