apiVersion: v1
kind: Secret
metadata:
  name: {{ include "appdeployment.name" . }}-secret
  namespace: {{ .Release.Namespace }}
data:
  DB_USER_NAME: {{ .Values.configVars.DbUserName }}
  DB_PASSWORD: {{ .Values.configVars.DbPassword }}

---
apiVersion: v1
data:
  .dockerconfigjson: {{ .Values.dockerConfigJson }}
kind: Secret
metadata:
  name: {{ .Values.imagePullSecretName }}
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson